version: '3.8'

services:
  ubuntu-desktop:
    build: .
    container_name: ubuntu-desktop-lxqt
    ports:
      - "5901:5901"
      - "8080:80"
    environment:
      - VNC_PASSWORD=123456
    restart: unless-stopped
