version: '3.8'

services:
  gatespy-analyzer:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: gatespy-analyzer
    ports:
      - "8000:8000"
    restart: unless-stopped
