services:

  windows:

    image: dockurr/windows

    container_name: windows

    environment:

      VERSION: "10"

      USERNAME: "MASTER"

      PASSWORD: "admin@123"

      RAM_SIZE: "4"

      CPU_CORES: "4"

      DISK_SIZE: "500G"

      DISK2_SIZE: "100G"

    devices:

      - /dev/kvm

      - /dev/net/tun

    cap_add:

      - NET_ADMIN

    ports:

      - "8080:8080"

      - "3389:3389/tcp"

      - "3389:3389/udp"

    stop_grace_period: 2m
