name: Build Buildroot Images

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x86, x86_64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y build-essential git wget curl python3 pkg-config bison flex gettext ncurses-dev

      - name: Download Buildroot
        run: |
          wget https://buildroot.org/downloads/buildroot-2023.02.1.tar.gz
          tar -xzf buildroot-2023.02.1.tar.gz
          mv buildroot-2023.02.1 buildroot

      - name: Configure Buildroot for ${{ matrix.arch }}
        run: |
          cd buildroot
          # Temel config oluşturuyoruz
          make defconfig

          # buildroot configsini düzenleyelim (örnek olarak temel paketleri ekliyoruz)
          # 'package' dizininde ilgili paketleri enable eden config satırlarını ekle:
          echo "BR2_PACKAGE_PYTHON3=y" >> .config
          echo "BR2_PACKAGE_CURL=y" >> .config
          echo "BR2_PACKAGE_WGET=y" >> .config
          echo "BR2_PACKAGE_IPUTILS_PING=y" >> .config
          echo "BR2_PACKAGE_GIT=y" >> .config
          echo "BR2_PACKAGE_SCREENFETCH=y" >> .config
          echo "BR2_PACKAGE_BASH=y" >> .config

          # Mimariye göre ayarlamalar
          if [ "${{ matrix.arch }}" = "x86" ]; then
            echo "BR2_i386=y" >> .config
            echo "BR2_x86_64=n" >> .config
          else
            echo "BR2_x86_64=y" >> .config
            echo "BR2_i386=n" >> .config
          fi

          # Yapılandırmayı senkronize et
          make olddefconfig

      - name: Build Buildroot for ${{ matrix.arch }}
        run: |
          cd buildroot
          make

      - name: Save defconfig file
        run: |
          cd buildroot
          cp .config output/defconfig-${{ matrix.arch }}

      - name: Upload defconfig artifact
        uses: actions/upload-artifact@v3
        with:
          name: defconfig-${{ matrix.arch }}
          path: buildroot/output/defconfig-${{ matrix.arch }}

      - name: Upload root filesystem image
        uses: actions/upload-artifact@v3
        with:
          name: rootfs-${{ matrix.arch }}
          path: buildroot/output/images/rootfs.ext4

      - name: Upload kernel image
        uses: actions/upload-artifact@v3
        with:
          name: kernel-${{ matrix.arch }}
          path: buildroot/output/images/bzImage

      - name: Upload disk image (if any)
        uses: actions/upload-artifact@v3
        with:
          name: disk-image-${{ matrix.arch }}
          path: buildroot/output/images/*.img
