name: Build Buildroot Images

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x86, x86_64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git wget curl python3 pkg-config bison flex gettext ncurses-dev

      - name: Download Buildroot
        run: |
          wget https://buildroot.org/downloads/buildroot-2023.02.1.tar.gz
          tar -xzf buildroot-2023.02.1.tar.gz
          mv buildroot-2023.02.1 buildroot

      - name: Configure Buildroot for ${{ matrix.arch }}
        run: |
          cd buildroot
          make defconfig

          # Temel paketleri aktif et
          scripts/config --enable BR2_PACKAGE_PYTHON3
          scripts/config --enable BR2_PACKAGE_CURL
          scripts/config --enable BR2_PACKAGE_WGET
          scripts/config --enable BR2_PACKAGE_IPUTILS_PING
          scripts/config --enable BR2_PACKAGE_GIT
          scripts/config --enable BR2_PACKAGE_SCREENFETCH
          scripts/config --enable BR2_PACKAGE_BASH

          # Mimariye göre ayar yap
          if [ "${{ matrix.arch }}" = "x86" ]; then
            scripts/config --enable BR2_i386
            scripts/config --disable BR2_x86_64
          else
            scripts/config --enable BR2_x86_64
            scripts/config --disable BR2_i386
          fi

          make olddefconfig

      - name: Build Buildroot for ${{ matrix.arch }}
        run: |
          cd buildroot
          make

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: buildroot-artifacts-${{ matrix.arch }}
          path: |
            buildroot/output/defconfig
            buildroot/output/images/rootfs.ext4
            buildroot/output/images/bzImage
            buildroot/output/images/*.img
